---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: engine-secrets
  namespace: default
spec:
  encryptedData:
    REDIS_URL: AgCWwax82CR0SxUOabPC8wftW+1oXbPOps2Hs9MPNIjafb59jlArxiF7XNfQ0bF9vpLrbSJIk/OUvz+dl6zZtmfLewWXVx8qDUeDnrEIgo3RLVqI53XHoPiCO6upHZxigUzWcmCR5bbNuG7o21j9oU6UGJwnJACs1b6qu2hc4wCCUniwIfhqHFjlOYTNl1r4DP9laUaURIQ6beG8M4kzem2dFIUOoANSAORJOnddfFO6XGbnIInUlkdZAHFrlHNulh/glc3V0W5LwP6pXmfSFKFddZ4sA3RcOWZO6zoMPOuMSJsDqFJflyYsWiHbzB4rKLzBsLSiHdRGXrpfZ0Cd1Wqq2nIiwqZ2BQNL+b7RtI2eMi0FWH32kmYJ4dwcqeEYaUCdvGcjhK5vFl8pPEYcQ7SMR+o1BWdPTfZWMBuPvueBQ8lNAGCumyOH3zr5D2HGoR+v3KTY+4zd1vMecyyooLIm/9QKiQkQ5q6X2TUg+MGAEnAPMcLUJcnFDwCPz4DV6wl+svKWnwrmQkmqiJ3tXGVQXEKbZiEClVswJvx0I/73C4x9QLB+t5x5DwO1EQyujfxxGqYEaiCVdN4DQ80/Cw8NzZ+gvMCsz+At0fDCaVTVRMP1ZTBaciI+LgglD3Ul+DFfWYEtmHOwCJ/hu6ccxOZb+LXaxnbyEUZg9p3TKW5DD7I6e1R0B/C2u34BvxkAV6IYhXwQ8Sx/RxuzCHK4mGnf93YLt2EatKiHDjLXudSB9UwS7JVa47rSU3Yt5M8rTJn5fPX/qT9ujqEhmuYZKLd96bZrOHI8eHJd7MPRyrrjlk0BZS3Q7Vypgkv9Gsjy/YrW6SQWywTFXBY=
  template:
    metadata:
      name: engine-secrets
      namespace: default
    type: Opaque
