apiVersion: v1
kind: ConfigMap
metadata:
  name: ws-config
data:
  NEXT_URL: "http://codesaga-client.default.svc.cluster.local:3000"
  PORT: "9090"
  STREAM_KEY: "codesaga:events:code"
  MAXLEN_APPROX: "10000"
  CLAIM_MIN_IDLE_MS: "15000"
  BULK_STREAM_KEY: "codesaga:events:db"
  BULK_MAXLEN_APPROX: "10000"
  BULK_CLAIM_MIN_IDLE_MS: "15000"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: codesaga-ws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codesaga-ws
  template:
    metadata:
      labels:
        app: codesaga-ws
    spec:
      containers:
      - name: ws
        image: jamesnagar/codesaga-ws:025fb782914b78c7e91ddd84a2b817c9f5d25dca
        ports:
        - containerPort: 9090
        envFrom:
        - configMapRef:
            name: ws-config
        - secretRef:
            name: ws-secrets
        resources:
          limits:
            cpu: "500m"
          requests:
            cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: codesaga-ws
  labels:
    app: codesaga-ws
spec:
  type: ClusterIP
  selector:
    app: codesaga-ws
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090