---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ws-secrets
  namespace: default
spec:
  encryptedData:
    REDIS_URL: AgBX/BwqnGlgqa7Rmp4GaeCs35KYIYWckTF2ujI7fW3ZbNUlF+Kel685y76Vpet/5N/Jv7A8h+LJZekPlPUXgftR4GRCSdvr+6lR/lHzk5JpSMGaEE8PIqv0lbAIS6/8qdo070zJKhqRHz1SiFxWvzIa1bU4pdH31RCpmO9mfwDZtNJsrVNzm+M6vJGwz8GOzv0rZpzBUxojq60BcXz/ALAnXbLZKWV0wW6KNhEY3ocaX3baQcRtr7bzZxe1+PdVXFR6at9ibL/Q1LT/fn92Vc0M/UqezyAyU1/b5kd5Y8P4Sh4S+mEkVtj9yo9F3DnQn0PQXCY++qr4zoTBaVo6KybVd8dDk0zffsHWFH8du0KRaYhxXGThT0YamdJEfqtdHwj6ct5nU5u3/Ya/srG1j5e4CdCSCG0n5ObP2m9cF1+7QepJbOPNVzuHMGG2yVpnwhXzNNhhr2qNQhH9BAh2VDhVxVfAVaLcqia5a6gMWR116On4BHHAu2Gk8blMKYjme2+1x+LK530RUZ8dDVa0DBYSoSjQuI63mXNTFWPaZWM7801xnmBVLHs/MIHqwE360F97LTu430XJXq3u9v/CCD0ddqQQn8rtQFqKmG/NdTRd068cnECoJdJ9YXzjJcslZwSDEFI4S1XLgPD09jb2MhNa4KE//Y2IFSMoTowSd/yFGcwMMGYTetorAMKuJguw4yXL9ao8AWALQi4M+ZdGsWjpEmH4FoTwyT5lyte75D1P7XOHk9y+d0hHNxPwtfQJ8ZTyYi2OENQe12eoPdLV6YxVBBFzYwMeKQUa4LbWEVkkSvpnJ6VCkMp3HD2NGqGlcvYHVPIyZ59DbJI=
  template:
    metadata:
      name: ws-secrets
      namespace: default
    type: Opaque
