---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bulk-master-secrets
  namespace: default
spec:
  encryptedData:
    REDIS_URL: AgAFY6ke9f5sxz6jWLKMtjR/lGCQotrkfuRuREmDdi9iYK/yvT8ZbDhiiZuxogqbhwVYbl6YGVfq/3wkGPwbcFpZDiEGrOaXr19INoSdpBFM91TG3A8aAM7radXbes6xJEGKByPP7M0OR3zSsr5h6X53U/XC5cqX/VrReHABbMBhL6YUOAL/pH113qeJty0whHfiZJkMIQ9x7EJdFes0pz4SDRsrFhxNN5Bdlzhljhr00xsERGjlU8IKrEhhygAXU3cZTBCTMh4A87U4Wi5NCByMP8vU8UZ2XTBo8h4LwHHl1wuWI5jSCvtMHsMFQVBJ1QnMiyvpWGRAjvNCRWaCHbtQ6E+H79uzx2nubLlepCtXk7HxxG2De8kg5qch4yIyvGUVmz0prVtZw97+ozoKoOAEs/8dVlTiOSGvYDPVE7AOYD1eAeN7O2K9bEt4Y5FV1mn7dHZY1Q9xR88oapl0ctN5x+5iIDLwL0ijtWMX95Xu7Da4uP9GUsf4Z9SgXdv23wmIVtqAr+ufBWp9PLHb9ofxHosVuBI+k5bq404WdLiDol9IDUqdgl7qS3+s4elPbGwLM4DL+uNhMoAX/hffyIUsszOsxrTAAh13G1Gq54sv24UWoGwsacfq+krLpMMtLFtJ/KISL7cwcU2Y7AQcaFQWz1Q4xB/8V4FIo8sTLA5au9YMyYem5UnqDJFsyIRZYray2OWTVjgr6lOTz8/I4uHSWdsgAuc8QFl6t4Whem25xsi/Jt2BueZjmHcw0gHpgOBEsa+fGec6R1XCtP/7yTZVrJxikUJvw7JCCx+uouCWdkdWDl5rLML1oSRzfdLQqhDm6uClACFXYf8=
  template:
    metadata:
      name: bulk-master-secrets
      namespace: default
    type: Opaque
