apiVersion: v1
kind: Secret
metadata:
  name: redis-keda-auth
  namespace: default
type: Opaque
data:
  redis-username: "ZGVmYXVsdA=="
  redis-password: "QVZOU19ib1JVTXM4cHhVVE5hMTFjOHM1"

---

apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: redis-keda-auth
  namespace: default

spec:
  secretTargetRef:
    - parameter: username
      name: redis-keda-auth
      key: redis-username

    - parameter: password
      name: redis-keda-auth
      key: redis-password

---

apiVersion: keda.sh/v1alpha1
kind: ScaledObject

metadata:
  name: codesaga-bulk-executor-scaler
  namespace: default

spec:
  scaleTargetRef:
    name: codesaga-bulk-executor

  minReplicaCount: 1
  maxReplicaCount: 10

  pollingInterval: 11
  cooldownPeriod: 20

  triggers:
    - type: redis-streams
      metadata:
        address: valkey-1a6340eb-princenagarjamescoc-04cb.i.aivencloud.com:21031
        stream: "codesaga:events:db"
        consumerGroup: "india-1"
        lagCount: "200"
        activationLagCount: "0"

      authenticationRef:
        name: redis-keda-auth