apiVersion: keda.sh/v1alpha1
kind: ScaledObject

metadata:
  name: codesaga-ws-scaler
  namespace: default

spec:
  scaleTargetRef:
    name: codesaga-ws   # scaled deployment name

  minReplicaCount: 1
  maxReplicaCount: 10

  pollingInterval: 15
  cooldownPeriod: 20

  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
        query: avg(codesaga_ws_active_users)
        threshold: "10000"
        activationThreshold: "0"