---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: client-secrets
  namespace: default
spec:
  encryptedData:
    .env: AgCM4TsdcbuijUnNbFDHOiHGVn2sEsPALvD211so9P5FSsIH8JFL0bWL/vNt2IwUHZT1aHB1aiXikSxojW0bLPgJHEoMoG7FSKBSNaD7KyzH4OTO1kcNn4VR4qSdOGl8sWJfZx0t5Aesrbutoh9MpKcBKAKaVirb5Rs0uDtTLzZuOTJZr9+vsAj4yD2/yTfZWbPjm0jGO9ATY2fMMdruRqEFeWycB0ZvS3zmo8ZsQACiNSmW3PN8Z6uGWR0Mi2Sv9jMYKgbYIYQB9v6i9te3X/Z9ANuRJ0jpvcR2GpMMBy33F19inYTa17E+N3984uS9KvUrDiRJDlqZdCxDVmgE/8iSkzI18EtSkiSm/kMJsWwbVftNW8yYg88lJg4XPTfok5SgBsNAdo80tlGcl9teFWwcYTK3L1NoE7LND/Ai8/GGuJRXBN6FhzF1yvf6lX+ueRdOuxDjcieOrk3FEzQhRe3xBpp6MZzn4qf/8DoMvF6UI56MmVs2zC+kxelKAp8gZIFdKkIq6Xraem6fuF3+VY3LkekvjHkEucMWekFQa1macSm2m4kbBsH2iU6DSsj4awoDEiV7xmrn3//1GomeKEYW1Wi8Bum++RNpB9KTIV4gX0JtrDtgr1jJNBVIYWoL+bTh1DLWOdTMDIMCUoR4oFU5V9lqYpbBTa1nbPqWY44mSnzhNezDx92l2KexhmJ7lbqD36NeDqChlgdeE4iKXN7SWZUj4Xeu3704CNyOs6t19aUv21g1vYQRH1E9EKpn5+Rmfh368lX8XetoUhBCxzz70S8RYvrOunBEXUKSYmYnh/kqewSL4dQOy6c4oFkFQ9f5eCSFtP4PNkmWpI2l0DjsKlPKFMklsT8rh9rw7r/Xns2bJ/dIwbr9LsM3KQ1zUe4rLCbmlEWifvtgnUaaJf9usabwaUii7gM/3BE3hSnG5xbsCDFtGOkRNEXBlWVnVEK7TcbFedvOhLKlFiEJ78k2rInKKJWsssd7uDXKGFSooE9xeQQd/dD1stRnjM4gKUTBn0sYE2xnNNGaCuqtJXsEC1mUnMf++PlduUKYKmW1+6+Izw1mlptiqb1nLvr7a5fXYhX09IGvnDxmhmFunoTCzikCq1SjIy4+JPhDdMzy1hcI3i/LuU47Rkp8sEg6Hm2AI9ZxkkvA+LRQt+JRxKJml86jCTpSqznsK1geUuuit5LAT4P9mBr/CjA6RHVnAx8NddpSCHip5fJvTO8SkN8TknYSvHEZjucQVgq2S1Ad8Vxeqb0JfJdEOb5jG46kSiD9y3G/hDxZXRZsSq4Nja/9rqpe6pb2pKcgdcGnW4U=
  template:
    metadata:
      name: client-secrets
      namespace: default
    type: Opaque
